services:
  mysql_accounts:
    image: mysql:8.0
    container_name: mysql_accounts
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: accounts_db
      MYSQL_USER: accounts_user
      MYSQL_PASSWORD: accounts_pass
    ports:
      - "3307:3306"
    networks:
      - bank_custom_network
    volumes:
      - mysql_accounts_data:/var/lib/mysql

  mysql_customers:
    image: mysql:8.0
    container_name: mysql_customers
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: customers_db
      MYSQL_USER: customers_user
      MYSQL_PASSWORD: customers_pass
    ports:
      - "3308:3306"
    networks:
      - bank_custom_network
    volumes:
      - mysql_customers_data:/var/lib/mysql

  mysql_keycloak:
    image: mysql:8.0
    container_name: mysql_keycloak
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak_db
      MYSQL_USER: keycloak_user
      MYSQL_PASSWORD: keycloak_pass
    networks:
      - bank_custom_network
    volumes:
      - mysql_keycloak_data:/var/lib/mysql

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    restart: always
    command: [ "start-dev" ]
    environment:
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://mysql_keycloak:3306/keycloak_db
      KC_DB_USERNAME: keycloak_user
      KC_DB_PASSWORD: keycloak_pass
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      - mysql_keycloak
    networks:
      - bank_custom_network

  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - bank_custom_network

networks:
  bank_custom_network:
    driver: bridge

volumes:
  mysql_accounts_data:
  mysql_customers_data:
  mysql_keycloak_data:
